version: "3"
services:
  db:
    image: postgres:latest
    container_name: "postgres-hotel"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
    ports:
      - "5433:5432/tcp"


  hotels:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - "db"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.31.233:5433/postgres
    ports:
      - "8080:8080"
